name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests and create artifact
        run: |
          if (!(Test-Path -Path ./artifacts)) { New-Item -ItemType Directory -Path ./artifacts }
          npm test > ./artifacts/test-results.txt 2>&1 || Write-Host "Tests completed with errors"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./artifacts/test-results.txt

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: ./artifacts

      - name: Display test results
        run: type ./artifacts/test-results.txt

      - name: Install dependencies and deploy
        run: |
          npm install
          npm install -g pm2
          pm2 restart app || pm2 start app.js --name "app"              
